### ISSUE TITLE
feat: 작업 기록 페이지 마크업

### ISSUE THREAD

**Issue by ahyeon-jung** [9oormthon-univ/2024_BEOTKKOTTHON_TEAM_28_FE#8]
## 💁‍♂️ ISSUE 개요

- 작업 기록 페이지 마크업

<br/>

## 📓 체크리스트

- [ ] 작업 기록 컴포넌트 분리
- [ ] 1차 스타일링

<br/>

## 📢 비고

- 팀 작업 기록/ 질문 목록 페이지 1차 작업 진행해서 main에 바로 올려놨습니다!
- 일단 메인 페이지+레이아웃 작업 끝나면 chakra-ui 커스텀 진행 에러 수정하겠습니다🌸🌸

**Comment by Sohyunnnn** [comment]
이거 작업 기록이 아니라 질문 목록에 해당하는 것 같습니다!! 
작업 기록 -> task-history
질문 목록 -> question-list

질문 목록에 대한 파일만 변경 되어있습니다!
